[package]
name = "amoret"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[target.x86_64-unknown-linux-musl]
linker = "clang"

[target.aarch64-unknown-linux-musl]
linker = "clang"

[target.riscv64gc-unknown-linux-musl]
linker = "clang"

[target.x86_64-pc-windows-msvc]
linker = "lld-link"

[target.aarch64-pc-windows-msvc]
linker = "lld-link"

[target.x86_64-apple-darwin]
linker = "clang"

[target.aarch64-apple-darwin]
linker = "clang"

[dependencies]
discord-rich-presence = "1.1.0"
steel-core = "0.8"
directories = "5"
toml = "0.8"
clap-verbosity-flag = "2.1"
simplelog = "0.12"
log = "0.4"

tokio = {
  version = "1",
  default-features = false,
  features = [
    "sync",
    "time",
    "rt-multi-thread",
    "macros"
  ]
}

serde = {
  version = "1",
  default-features = false,
  features = [
    "derive",
    "std"
  ]
}

clap = {
  version = "4",
  default-features = false,
  features = [
    "derive",
    "help",
    "usage",
    "error-context"
  ]
}
