[package]
name = "amoret"
version = "1.0.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/s0me1newithhand7s/amoret"
description = "Simple Discord RPC daemon written on rust."
default-run = "amoret"
authors = ["s0me1newithhand7s me+git@hand7s.org"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
discord-rich-presence = "1.1.0"
steel-core = "0.8.2"
directories = "6"
toml = "1.1"
clap-verbosity-flag = "3.0"
simplelog = "0.12"
log = "0.4"
sysinfo = "0.39.6"

tokio = {
  version = "1",
  default-features = false,
  features = [
    "sync",
    "time",
    "rt-multi-thread",
    "macros"
  ]
}

serde = {
  version = "1",
  default-features = false,
  features = [
    "derive",
    "std"
  ]
}

clap = {
  version = "4",
  default-features = false,
  features = [
    "derive",
    "help",
    "usage",
    "error-context"
  ]
}
