---
name: PR JOB

on:
  merge_group:
  
  pull_request:
    branches: [ "*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  BIN_NAME: amoret

permissions:
  contents: read

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: checkput
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: install nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342
        with:
          extra_nix_config: |
            extra-experimental-features = nix-command flakes

      - name: linter run
        shell: bash
        run: |
          mkdir -p "./.devenv"
          
          printf "%s" "$PWD" > "./.devenv/root"

          nix --extra-experimental-features "nix-command flakes" \
            develop .#default --no-pure-eval \
            --accept-flake-config \
            --override-input devenv-root "file+file://$(pwd)/.devenv/root" \
            --command prek run --fail-fast --all-files

  matrix-test-build-run:
    name: fail-slow (${{ matrix.target }})
    needs: lint 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            use_cross: true
          
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            use_cross: true
          
          - os: ubuntu-latest
            target: riscv64gc-unknown-linux-musl
            use_cross: true
          
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use_cross: false

          - os: windows-latest
            target: aarch64-pc-windows-msvc
            use_cross: false
          
          - os: macos-15-intel
            target: x86_64-apple-darwin
            use_cross: false

          - os: macos-latest
            target: aarch64-apple-darwin
            use_cross: false

    steps:
      - name: checkput
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: rust toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
        with:
          targets: ${{ matrix.target }}
          toolchain: stable

      - name: cross-rs
        if: matrix.use_cross == true
        run: cargo install cross --git https://github.com/cross-rs/cross --verbose

      - name: cargo-nextest
        run: cargo install cargo-nextest --git https://github.com/nextest-rs/nextest --verbose

      - name: testing
        shell: bash
        run: |
          if [ "${{ matrix.use_cross }}" = "true" ]; then
            cross test --release --locked --target ${{ matrix.target }} --fail-fast
          else
            cargo nextest run --release --locked --target ${{ matrix.target }} --fail-fast
          fi

      - name: building
        shell: bash
        run: |
          if [ "${{ matrix.use_cross }}" = "true" ]; then
            cross build --release --locked --target ${{ matrix.target }}
          else
            cargo build --release --locked --target ${{ matrix.target }}
          fi

      - name: runnig
        if: matrix.target != 'aarch64-pc-windows-msvc'
        shell: bash
        run: |
          if [ "${{ matrix.use_cross }}" = "true" ]; then
            timeout 5 cross run --release --locked --target ${{ matrix.target }} -- --config ./config.toml -vvv
          else
            timeout 5 cargo run --release --locked --target ${{ matrix.target }} -- --config ./config.toml -vvv
          fi
          
          EXIT_CODE=$?
          if [ $EXIT_CODE -eq 124 ]; then
            echo "✅ amoret succseeded"
            exit 0
          else
            echo "❌ amoret failed $EXIT_CODE"
            exit $EXIT_CODE
          fi
  
  all-tests-passed:
    name: "Required - No Failed Checks"
    needs: [ lint, matrix-test-build-run ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check matrix status
        run: |
          if [ "${{ needs.matrix-test-build-run.result }}"="success" ]; then
            echo "All matrix tests passed successfully."
            exit 0
          else
            echo "One or more matrix tests failed."
            exit 1
          fi
