---
name: pr handle job

on:
  workflow_dispatch:

  merge_group:
  
  pull_request:
    branches: [ "*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  BIN_NAME: amoret

permissions:
  contents: read

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: checkput
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: install nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342
        with:
          extra_nix_config: |
            extra-experimental-features = nix-command flakes

      - name: magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@55718cd9ebf1737a061487d5ada21abf31e99a98

      - name: cargo update
        shell: bash
        run: |
          mkdir -p "./.devenv"
          
          printf "%s" "$PWD" > "./.devenv/root"

          nix --extra-experimental-features "nix-command flakes" \
            develop .#default --no-pure-eval \
            --accept-flake-config \
            --override-input devenv-root "file+file://$(pwd)/.devenv/root" \
            --command cargo fetch --locked

      - name: linter run
        shell: bash
        run: |
          mkdir -p "./.devenv"
          
          printf "%s" "$PWD" > "./.devenv/root"

          nix --extra-experimental-features "nix-command flakes" \
            develop .#default --no-pure-eval \
            --accept-flake-config \
            --override-input devenv-root "file+file://$(pwd)/.devenv/root" \
            --command prek run --fail-fast --all-files

  matrix-test-build-run:
    name: fail-slow (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            is_nt: false
          
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            is_nt: false
          
          - os: ubuntu-latest
            target: riscv64gc-unknown-linux-musl
            is_nt: false
          
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            is_nt: true
          
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            is_nt: true
          
          - os: macos-15-intel
            target: x86_64-apple-darwin
            is_nt: false
          
          - os: macos-latest 
            target: aarch64-apple-darwin
            is_nt: false

    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: install nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342
        with:
          extra_nix_config: |
            extra-experimental-features = nix-command flakes

      - name: magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@55718cd9ebf1737a061487d5ada21abf31e99a98

      - name: build-nt
        if: matrix.is_nt == true
        shell: bash
        run: |
          nix --extra-experimental-features "nix-command flakes" \
            develop --no-pure-eval --accept-flake-config \
            --command cargo xwin build --release --target ${{ matrix.target }}

      - name: build-unix
        if: matrix.is_nt == false
        shell: bash
        run: |
          nix --extra-experimental-features "nix-command flakes" \
            develop --no-pure-eval --accept-flake-config \
            --command cargo zigbuild --release --target ${{ matrix.target }}

  all-tests-passed:
    name: req - no jobs failed
    needs: [ lint, matrix-test-build-run ]
    runs-on: ubuntu-latest
    if: always()
    permissions:
      statuses: write
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3
        env:
          RESULTS: ${{ toJSON(needs.*.result) }}
        with:
          script: |
            const { serverUrl, repo, runId, payload } = context
            const target_url = `${serverUrl}/${repo.owner}/${repo.repo}/actions/runs/${runId}`
            
            const resultsObj = JSON.parse(process.env.RESULTS);
            const allPassed = Object.values(resultsObj).every(status => status === 'success');
            const state = allPassed ? 'success' : 'error';

            await github.rest.repos.createCommitStatus({
              ...repo,
              sha: context.sha,
              context: 'req - no jobs failed',
              state: state,
              target_url: target_url,
              description: allPassed ? 'All checks passed!' : 'One or more jobs failed.'
            })
...
