---
name: RELEASE JOB

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

env:
  CARGO_TERM_COLOR: always
  BIN_NAME: amoret

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  build:
    name: build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            use_cross: true
          
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            use_cross: true
          
          - os: ubuntu-latest
            target: riscv64gc-unknown-linux-musl
            use_cross: true
          
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use_cross: false
          
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            use_cross: false
          
          - os: macos-15-intel
            target: x86_64-apple-darwin
            use_cross: false
          
          - os: macos-latest 
            target: aarch64-apple-darwin
            use_cross: false

    steps:
      - name: chechout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: rust toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
        with:
          targets: ${{ matrix.target }}
          toolchain: stable

      - name: cross-rs
        if: matrix.use_cross == true
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: build
        shell: bash
        run: |
          if [ "${{ matrix.use_cross }}" = "true" ]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi

      - name: artifact prep
        shell: bash
        run: |
          mkdir -p staging
          if [ "${{ runner.os }}" = "Windows" ]; then
            cp target/${{ matrix.target }}/release/${{ env.BIN_NAME }}.exe staging/
          else
            cp target/${{ matrix.target }}/release/${{ env.BIN_NAME }} staging/
          fi
          tar -caf ${{ env.BIN_NAME }}-${{ matrix.target }}.tar.zstd -C staging .

      - name: attest build
        uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373
        with:
          subject-path: ${{ env.BIN_NAME }}-${{ matrix.target }}.tar.zstd

      - name: attest upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: ${{ env.BIN_NAME }}-${{ matrix.target }}
          path: ${{ env.BIN_NAME }}-${{ matrix.target }}.tar.zstd

  release:
    name: release
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: fetch artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          path: release-assets
          merge-multiple: true

      - name: gha release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228
        with:
          token: ${{ secrets.PAT_TOKEN }}
          files: release-assets/*.tar.zstd
          generate_release_notes: true
---
