---
name: UPDATE JOB

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-cargo:
    name: update-cargo
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: rust toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9

      - name: cargo update
        run: cargo update --verbose

      - name: pull requrest
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        with:
          token: ${{ secrets.GHA_TOKEN }}
          commit-message: "chore(deps): update cargo dependencies"
          title: "chore(deps): update dependencies"
          body: |
            Automated dependency updates triggered by `cargo update`.
            Please review the lockfile changes and ensure CI passes.
          branch: update-cargo-deps
          base: master

  update-nix:
    name: update-nix
    runs-on: ubuntu-latest
    steps:
      - name: checkot
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: nix install
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342
        with:
          extra_nix_config: |
            extra-experimental-features = nix-command flakes

      - name: nix flake update
        run: nix flake update --accept-flake-config

      - name: pr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        with:
          token: ${{ secrets.GHA_TOKEN }}
          commit-message: "build(nix): update flake inputs"
          title: "chore(deps): update flake lock"
          body: |
            Automated update of `flake.lock` triggered by `nix flake update`.
            Please review the lockfile changes and ensure CI passes.
          branch: update-nix-flake
          base: master 

  update-github-actions:
    name: Update CI/CD Workflows
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: setup deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed
        with:
          deno-version: v2.x
          cache: true

      - name: update actions 
        run: deno dx actions-up --write
      
      - name: pr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        with:
          token: ${{ secrets.GHA_TOKEN }}
          commit-message: "ci(actions): bump github actions versions"
          title: "ci(actions): bump github actions versions"
          body: |
            Automated bump of `uses:` statements in `.github/workflows/` to their latest stable releases.
            Please review the `*.yaml` changes and ensure CI passes.
          branch: update-github-actions
          base: master
