---
on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-cargo:
    name: update-cargo
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: rust toolchain
        uses: dtolnay/rust-toolchain@b2b36207fb4d11c9373a6e7c38b6f5f2e4ea0f9e

      - name: cargo update
        run: cargo update --verbose

      - name: pull requrest
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc838f5cc0
        with:
          token: ${{ secrets.GHA_TOKEN }}
          commit-message: "chore(deps): update cargo dependencies"
          title: "chore(deps): update dependencies"
          body: |
            Automated dependency updates triggered by `cargo update`.
            Please review the lockfile changes and ensure CI passes.
          branch: update-cargo-deps
          base: master

  update-nix:
    name: update-nix
    runs-on: ubuntu-latest
    steps:
      - name: checkot
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: nix install
        uses: cachix/install-nix-action@3715ab1a11cac9e991980d7b7a428d8dd745496d
        with:
          extra_nix_config: |
            extra-experimental-features = nix-command flakes

      - name: nix flake update
        run: nix flake update --accept-flake-config

      - name: pr
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc838f5cc0
        with:
          token: ${{ secrets.GHA_TOKEN }}
          commit-message: "build(nix): update flake inputs"
          title: "chore(deps): update flake lock"
          body: |
            Automated update of `flake.lock` triggered by `nix flake update`.
            Please review the lockfile changes and ensure CI passes.
          branch: update-nix-flake
          base: master 

  update-github-actions:
    name: Update CI/CD Workflows
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: setup deno
        uses: denoland/setup-deno@4a92d41a774db8cfc7a022dfa022d2fca038c116
        with:
          deno-version: v2.x
          cache: true

      - name: update actions 
        run: deno dx actions-up --write
      
      - name: pr
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc838f5cc0
        with:
          token: ${{ secrets.GHA_TOKEN }}
          commit-message: "ci(actions): bump github actions versions"
          title: "ci(actions): bump github actions versions"
          body: |
            Automated bump of `uses:` statements in `.github/workflows/` to their latest stable releases.
            Please review the `*.yaml` changes and ensure CI passes.
          branch: update-github-actions
          base: master
